-- MySQL Script generated by MySQL Workbench
-- Thu Jul  4 13:04:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema anime
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `usuario` (
  `Id_usu` VARCHAR(10) NOT NULL,
  `Nombre` TEXT NULL DEFAULT NULL,
  `Apell` TEXT NULL DEFAULT NULL,
  `psw` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_usu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `clientes` (
  `Id_cliente` VARCHAR(10) NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `N_Documento` INT(11) NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `Tel` INT(10) NOT NULL,
  `Dir` VARCHAR(50) NOT NULL,
  `Ciudad` TEXT NOT NULL,
  `Id_usu` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `tipo_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tipo_producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `tipo_producto` (
  `Id_Producto` VARCHAR(10) NOT NULL,
  `Tipo` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Bodega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bodega` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Bodega` (
  `Id_bodega` VARCHAR(10) NOT NULL,
  `Dept` VARCHAR(15) NOT NULL,
  `Municipio` VARCHAR(15) NOT NULL,
  `Tel` INT(10) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_bodega`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Tienda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tienda` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Tienda` (
  `Id_tienda` VARCHAR(10) NOT NULL,
  `Tienda` VARCHAR(10) NOT NULL,
  `Dept` VARCHAR(15) NOT NULL,
  `Tel` INT(10) NOT NULL,
  `Direccion` VARCHAR(50) NOT NULL,
  `Id_bodega` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_tienda`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `producto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `producto` (
  `Id_producto` VARCHAR(10) NOT NULL,
  `Cod_producto` INT(11) NOT NULL,
  `Descripcion` VARCHAR(80) NOT NULL,
  `Valor_uni` INT(11) NOT NULL,
  `Costo` INT(11) NOT NULL,
  `Cantidad_llego` INT(11) NOT NULL,
  `Cantidad_actual` INT(11) NOT NULL,
  `Tipo_producto` VARCHAR(50) NOT NULL,
  `Id_tienda` INT(10) NOT NULL,
  `Id_usu` VARCHAR(10) NOT NULL,
  `Imagen` INT(11) NOT NULL,
  `Id_tienda` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `Id_tienda` ON `producto` (`Id_tienda` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `devolucion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devolucion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `devolucion` (
  `Id_Devolucion` VARCHAR(10) NOT NULL,
  `Id_Producto` VARCHAR(10) NOT NULL,
  `Fecha_Devolu` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id_Devolucion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `Id_Producto_2` ON `devolucion` (`Id_Producto` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfil` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `perfil` (
  `Id_per_usu` VARCHAR(10) NOT NULL,
  `Tipo_perfil` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`Id_per_usu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfil_usu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `perfil_usu` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `perfil_usu` (
  `Id_tip_perfil_us` VARCHAR(10) NULL DEFAULT NULL,
  `Id_usu` VARCHAR(10) NULL DEFAULT NULL,
  `Id_per_usu` VARCHAR(10) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Traslado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Traslado` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Traslado` (
  `Id_traslado` VARCHAR(10) NOT NULL,
  `Id_tienda_actual` VARCHAR(10) NOT NULL,
  `Id_tienda_nueva` VARCHAR(10) NOT NULL,
  `Id_producto` VARCHAR(10) NOT NULL,
  `Fecha_traslado` DATETIME NOT NULL,
  PRIMARY KEY (`Id_traslado`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Inventario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Inventario` (
  `Id_tienda` INT NOT NULL,
  `Id_producto` VARCHAR(10) NOT NULL,
  `Cantidad_llego` VARCHAR(40) NOT NULL,
  `Cantidad_actual` VARCHAR(40) NOT NULL,
  `Fecha_mod` DATETIME NOT NULL,
  PRIMARY KEY (`Id_tienda`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Venta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Venta` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `Venta` (
  `Id_venta` INT NOT NULL,
  `Id_cliente` VARCHAR(45) NOT NULL,
  `Id_Producto` VARCHAR(45) NOT NULL,
  `Id_usu` VARCHAR(45) NOT NULL,
  `usuario_Id_usu` VARCHAR(10) NOT NULL,
  `clientes_Id_cliente` VARCHAR(10) NOT NULL,
  `producto_Id_producto` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Id_venta`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
